INSERT INTO category (category_Name) VALUES ('American');
INSERT INTO category (category_Name) VALUES ('Italian');
INSERT INTO category (category_Name) VALUES ('Mexican');
INSERT INTO category (category_Name) VALUES ('Fast Food');
INSERT INTO unite_of_mesure (uom) VALUES ('Teaspoon');
INSERT INTO unite_of_mesure (uom) VALUES ('Tablespoon');
INSERT INTO unite_of_mesure (uom) VALUES ('Cup');
INSERT INTO unite_of_mesure (uom) VALUES ('Ounce');
INSERT INTO unite_of_mesure (uom) VALUES ('Dash');
INSERT INTO unite_of_mesure (uom) VALUES ('Pint');
INSERT INTO unite_of_mesure (uom) VALUES ('Each');